[base]
    env="prod"
    debug_mode="release"
    time_location="Asia/Shanghai"

[http]
    addr =":8081"                       # 监听地址, default ":8700"
    read_timeout = 10                   # 读取超时时长
    write_timeout = 30                  # 写入超时时长
    max_header_bytes = 20               # 最大的header大小，二进制位长度

[log]
    log_level = "trace"         #日志打印最低级别

[mysql]
    driver_name = "mysql"
    data_source_name = "root:123@tcp(localhost:3306)/bastion?charset=utf8mb4&parseTime=true&loc=Asia%2FChongqing"
    max_open_conn = 20
    max_idle_conn = 10
    max_conn_life_time = 100

[redis]
    address = ""
    password = ""
