base:
    is_dev : false
out_dir : ./model  # 输出目录
url_tag : json # web url tag(json,db(https://github.com/google/go-querystring))
language : 中 文 # 语言(English,中 文)
db_tag : gorm # 数据库标签(gorm,db)
singular_table : true  # 单表模式:true:禁用表名复数,false:采用表名复数 参考:gorm.SingularTable
simple : true # 简单输出(默认gorm标签不输出)
is_out_sql : false # 是否输出 sql 原信息
is_out_func : false # 是否输出 快捷函数
is_web_tag : true # 是否打web标记(json标记前提条件)
is_foreign_key : false # 是否导出外键关联
is_gui : false # 是否ui模式显示
is_table_name : true # 是否直接生成表名函数
mysql_info:
    host :
    port : 3306
    username : root
    password :
    database : deja

